name: Feed-Find
version: 0.06
abstract: Syndication Feed Discovery
author: Benjamin Trott <ben+cpan@stupidfool.org>
license: perl
distribution_type: module
requires:
  Class::ErrorHandler: 0
  LWP: 0
  HTML::Parser: 0
  URI: 0
no_index:
  directory:
    - t
    - inc
generated_by: Module::Install version 0.36
